### ISSUE TITLE
CI wheel building fails for python 3.7+

### ISSUE THREAD

**Issue by jmduarte** [scikit-hep/fastjet#106]
Running wheel building with `cibuildwheel==2.11.1` [locally](https://cibuildwheel.readthedocs.io/en/stable/setup/#local), I made some observations

- `cp36-manylinux_x86_64`: passes build wheel and repair wheel
- `cp37-manylinux_x86_64`: passes build wheel and fails repair wheel
- `cp38-manylinux_x86_64`: passes build wheel and fails repair wheel
- `cp39-manylinux_x86_64`: passes build wheel and fails repair wheel

The error messages for python 3.7+ are all minor variations of https://github.com/scikit-hep/fastjet/actions/runs/3175179383/jobs/5172897042
(sometimes it's a different shared library that can't be found).
```
Repairing wheel...
 
      + sh -c 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/fastjet-3.3.4.0rc9-cp39-cp39-linux_x86_64.whl'
  INFO:auditwheel.main_repair:Repairing fastjet-3.3.4.0rc9-cp39-cp39-linux_x86_64.whl
  Traceback (most recent call last):
    File "/usr/local/bin/auditwheel", line 8, in <module>
      sys.exit(main())
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/main.py", line 51, in main
      rval = args.func(args, p)
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/main_repair.py", line 123, in execute
      out_wheel = repair_wheel(args.WHEEL_FILE,
    File "/opt/_internal/pipx/venvs/auditwheel/lib/python3.9/site-packages/auditwheel/repair.py", line 67, in repair_wheel
      raise ValueError(('Cannot repair wheel, because required '
  ValueError: Cannot repair wheel, because required library "libfastjettools.so.0" could not be located
                                                              ✕ 1.40s
Error: Command ['sh', '-c', 'auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/fastjet-3.3.4.0rc9-cp39-cp39-linux_x86_64.whl'] failed with code 1. 

Error: Process completed with exit code 1.
```

Next step I think is to manually run the commands in a `quay.io/pypa/manylinux2014_x86_64` container (or increase verbosity) to see what issues may be happening, i.e.
```bash
yum update -y && yum install -y mpfr-devel boost-devel^C
mkdir -p /tmp/cibuildwheel/built_wheel
python -m pip wheel /project --wheel-dir=/tmp/cibuildwheel/built_wheel --no-deps
mkdir -p /tmp/cibuildwheel/repaired_wheel
auditwheel repair -w /tmp/cibuildwheel/repaired_wheel /tmp/cibuildwheel/built_wheel/fastjet-3.3.4.0rc9-cp39-cp39-linux_x86_64.whl
```
`auditwheel` also apparently has some additional tools that can help with debugging.

**Comment by jmduarte** [comment]
Some additional data:

I seem to be able to repair the wheel in 3.10 locally (`cibuildwheel --only cp310-manylinux_x86_64`) by setting the `LD_LIBRARY_PATH`: 
https://github.com/scikit-hep/fastjet/blob/17a5651dc19c14d425d0fda4a2aa94de67a778c1/pyproject.toml#L21
but this still see to fail in the GitHub action (https://github.com/scikit-hep/fastjet/actions/runs/3260068169/jobs/5353349759).

I also checked what the repaired wheel I built locally ([tree_new_wheel.txt](https://github.com/scikit-hep/fastjet/files/9795163/tree_new_wheel.txt)) looks like compared to the one on PyPI (
[tree_PyPI_wheel.txt](https://github.com/scikit-hep/fastjet/files/9795162/tree_PyPI_wheel.txt)) and I clearly see some differences. The most significant of which I think is `_fastjet.so` is not being included in the right directory, and `fastjet.py` is not being included as `_swig.py` in the right directory.

```diff
3,5c3
< │   ├── __init__.py
< │   ├── _ext.cpython-39-x86_64-linux-gnu.so
< │   ├── _fastjet.so
---
> │   ├── _ext.cpython-310-x86_64-linux-gnu.so
11d8
< │   │   │   │   ├── ATLASConePlugin.hh
13a11
> │   │   │   │   ├── ATLASConePlugin.hh
16d13
< │   │   │   │   ├── CMSIterativeConePlugin.hh
18d14
< │   │   │   │   ├── ClusterSequence.hh
20d15
< │   │   │   │   ├── ClusterSequenceActiveArea.hh
22c17
< │   │   │   │   ├── ClusterSequenceArea.hh
---
> │   │   │   │   ├── ClusterSequenceActiveArea.hh
23a19,20
> │   │   │   │   ├── ClusterSequenceArea.hh
> │   │   │   │   ├── ClusterSequence.hh
27a25
> │   │   │   │   ├── CMSIterativeConePlugin.hh
28a27,28
> │   │   │   │   ├── config_auto.h
> │   │   │   │   ├── config.h
38,58d37
< │   │   │   │   ├── JadePlugin.hh
< │   │   │   │   ├── JetDefinition.hh
< │   │   │   │   ├── LimitedWarning.hh
< │   │   │   │   ├── NNBase.hh
< │   │   │   │   ├── NNFJN2Plain.hh
< │   │   │   │   ├── NNFJN2Tiled.hh
< │   │   │   │   ├── NNH.hh
< │   │   │   │   ├── NestedDefsPlugin.hh
< │   │   │   │   ├── PseudoJet.hh
< │   │   │   │   ├── PseudoJetStructureBase.hh
< │   │   │   │   ├── RangeDefinition.hh
< │   │   │   │   ├── RectangularGrid.hh
< │   │   │   │   ├── SISConeBasePlugin.hh
< │   │   │   │   ├── SISConePlugin.hh
< │   │   │   │   ├── SISConeSphericalPlugin.hh
< │   │   │   │   ├── Selector.hh
< │   │   │   │   ├── SharedPtr.hh
< │   │   │   │   ├── TrackJetPlugin.hh
< │   │   │   │   ├── WrappedStructure.hh
< │   │   │   │   ├── config.h
< │   │   │   │   ├── config_auto.h
59a39
> │   │   │   │   │   ├── base.hh
61d40
< │   │   │   │   │   ├── ClosestPair2D.hh
62a42,43
> │   │   │   │   │   ├── ClosestPair2D.hh
> │   │   │   │   │   ├── deprecated.hh
70d50
< │   │   │   │   │   ├── LazyTiling9.hh
71a52
> │   │   │   │   │   ├── LazyTiling9.hh
74a56
> │   │   │   │   │   ├── numconsts.hh
78,81c60,77
< │   │   │   │   │   ├── Voronoi.hh
< │   │   │   │   │   ├── base.hh
< │   │   │   │   │   ├── deprecated.hh
< │   │   │   │   │   └── numconsts.hh
---
> │   │   │   │   │   └── Voronoi.hh
> │   │   │   │   ├── JadePlugin.hh
> │   │   │   │   ├── JetDefinition.hh
> │   │   │   │   ├── LimitedWarning.hh
> │   │   │   │   ├── NestedDefsPlugin.hh
> │   │   │   │   ├── NNBase.hh
> │   │   │   │   ├── NNFJN2Plain.hh
> │   │   │   │   ├── NNFJN2Tiled.hh
> │   │   │   │   ├── NNH.hh
> │   │   │   │   ├── PseudoJet.hh
> │   │   │   │   ├── PseudoJetStructureBase.hh
> │   │   │   │   ├── RangeDefinition.hh
> │   │   │   │   ├── RectangularGrid.hh
> │   │   │   │   ├── Selector.hh
> │   │   │   │   ├── SharedPtr.hh
> │   │   │   │   ├── SISConeBasePlugin.hh
> │   │   │   │   ├── SISConePlugin.hh
> │   │   │   │   ├── SISConeSphericalPlugin.hh
88d83
< │   │   │   │   │   ├── JHTopTagger.hh
89a85
> │   │   │   │   │   ├── JHTopTagger.hh
97c93,95
< │   │   │   │   └── version.hh
---
> │   │   │   │   ├── TrackJetPlugin.hh
> │   │   │   │   ├── version.hh
> │   │   │   │   └── WrappedStructure.hh
110d107
< │   │   │       ├── siscone.h
111a109
> │   │   │       ├── siscone.h
125,127d122
< │   │       ├── libfastjet.so
< │   │       ├── libfastjet.so.0
< │   │       ├── libfastjet.so.0.0.0
132a128,130
> │   │       ├── libfastjet.so
> │   │       ├── libfastjet.so.0
> │   │       ├── libfastjet.so.0.0.0
147c145,156
< │   │       └── libsiscone_spherical.so.0.0.0
---
> │   │       ├── libsiscone_spherical.so.0.0.0
> │   │       └── python3.10
> │   │           └── site-packages
> │   │               ├── _fastjet.a
> │   │               ├── _fastjet.la
> │   │               ├── fastjet.py
> │   │               ├── _fastjet.so
> │   │               ├── _fastjet.so.0
> │   │               ├── _fastjet.so.0.0.0
> │   │               └── __pycache__
> │   │                   ├── fastjet.cpython-310.opt-1.pyc
> │   │                   └── fastjet.cpython-310.pyc
148a158
> │   ├── __init__.py
152d161
< │   ├── _swig.py
159,160c168,169
< │   ├── WHEEL
< │   └── top_level.txt
---
> │   ├── top_level.txt
> │   └── WHEEL
162c171,175
< │   └── libgmp-afec2dd4.so.10.2.0
---
> │   ├── libfastjet-35dd70fe.so.0.0.0
> │   ├── libfastjettools-867586c1.so.0.0.0
> │   ├── libgmp-afec2dd4.so.10.2.0
> │   ├── libsiscone-18a46231.so.0.0.0
> │   └── libsiscone_spherical-83bd7ed9.so.0.0.0
165c178
< 12 directories, 150 files
---
> 15 directories, 160 files
```

My impression is this is intended to be done here: https://github.com/scikit-hep/fastjet/blob/cdc7851dc848005608e778d3dbbb834332e3893a/setup.py#L118-L119
but perhaps this then relies on some deprecated behavior of `setuptools` like this: https://setuptools.pypa.io/en/stable/history.html#id135

@henryiii do you have any suggestions or ideas on how to fix this?

**Comment by chrispap95** [comment]
Hi @jmduarte, that's my impression as well. It seems that for the failing workflows buildwheel is installing in directories that look like `lib.linux-x86_64-cpython-310` while `setup.py` expects something like `lib.linux-x86_64-3.10` because it defines: ```python
version = ".".join(map(str, sys.version_info[:2]))
plat = sysconfig.get_platform()
fastjetdir = pathlib.Path(f"build/lib.{plat}-{version}/fastjet")
```
Perhaps we could fix (somehow) the latter instead of downgrading the setuptools version? Unfortunately I didn't have time to investigate further.

**Comment by henryiii** [comment]
Ahh, yes,

```python
version = ".".join(map(str, sys.version_info[:2]))
plat = sysconfig.get_platform()
fastjetdir = pathlib.Path(f"build/lib.{plat}-{version}/fastjet")
```

Changed to be more specific (which fixed pypy, since before then they collided).

I think we should try to the the CI working again (#108), then see if we can fix this as a second step.

**Comment by chrispap95** [comment]
@henryiii thanks for the reply! I noticed this a few days ago but I didn't take any action because hardcoding the change in the string seemed like the wrong approach. I see that awkward is doing

```python
outerdir = os.path.join(
    os.path.join(
        "build",
        "lib.{}-{}.{}".format(
            get_platform(),
            sys.version_info[0],
            sys.version_info[1],
        ),
    )
)
```

Is this a truly universal approach? I am asking because my system python seems to be handling this differently than my pyenv-compiled python.
