### ISSUE TITLE
Local build from source error for CentOS and Ubuntu

### ISSUE THREAD

**Issue by rkansal47** [scikit-hep/fastjet#138]
I have tried to build from source on the following OS versions:

```
Ubuntu 20.04.2 LTS
CentOS Linux 7
Scientific Linux 7.9
```

having installed the dependencies listed here https://github.com/scikit-hep/fastjet#build-dependencies.

I received the same error on each:

```
Traceback (most recent call last):
    File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 412, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 150, in <module>
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-h8ix18u2/normal/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 324, in run
      self.run_command("build")
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/tmp/pip-build-env-h8ix18u2/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
      self.build_extensions()
    File "<string>", line 88, in build_extensions
    File "/opt/conda/lib/python3.9/subprocess.py", line 528, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['./autogen.sh', '--prefix=/tmp/pip-req-build-b8lereps/src/fastjet/_fastjet_core', '--enable-allcxxplugins', '--enable-cgal-header-only', '--enable-cgal', '--with-cgaldir=/tmp/pip-req-build-b8lereps/CGAL-5.5.1', '--enable-swig', '--enable-pyext', 'LDFLAGS=-Wl,-rpath=$$ORIGIN/_fastjet_core/lib:$$ORIGIN']' returned non-zero exit status 1.
```

**Comment by lgray** [comment]
That may also now require gmp-dev and mpfr-dev. Could you try adding those?

**Comment by rkansal47** [comment]
Ah, indeed that worked, thanks!
