### ISSUE TITLE
cluster.constituent_index can generate awkard arrays with uninitialized data, leading to crashes in awkward 

### ISSUE THREAD

**Issue by jpata** [scikit-hep/fastjet#174]
`cluster.constituent_index` can generate arrays with uninitialized data, leading to crashes in awkward 

```python
import awkward as ak
import uproot
import fastjet
import vector
print("uproot", uproot.__version__)
print("awkward", ak.__version__)
print("fastjet", fastjet.__version__)
print("vector", vector.__version__)

if __name__ == "__main__":
    #wget from https://jpata.web.cern.ch/jpata/mlpf/clic_edm4hep/reco_p8_ee_ZH_Htautau_ecm380_1.root
    fi = uproot.open("reco_p8_ee_ZH_Htautau_ecm380_1.root")
    ev = fi["events"]
    arrs = ev.arrays(["MergedRecoParticles"])

    # Prepare 4-momentum of reco particles
    mrp = arrs["MergedRecoParticles"]
    mrp = ak.Record({k.replace("MergedRecoParticles.", ""): mrp[k] for k in mrp.fields})
    reco_p4 = vector.awk(
        ak.zip({"mass": mrp["mass"], "x": mrp["momentum.x"], "y": mrp["momentum.y"], "z": mrp["momentum.z"]})
    )

    # Cluster AK4 jets from PF particles with min pt 5 GeV
    jetdef = fastjet.JetDefinition(fastjet.antikt_algorithm, 0.4)
    cluster = fastjet.ClusterSequence(reco_p4, jetdef)
    constituent_idx = cluster.constituent_index(min_pt=5.0)
    print(constituent_idx.layout.content.offsets.data)

    #since offsets are filled with partly uninitialized values, flatten fails
    constituents_flat = ak.flatten(constituent_idx, axis=-1) 
    p4_flat = reco_p4[constituents_flat]
```
leads to

```
uproot 5.0.2
awkward 2.0.6
fastjet 3.4.0.4
vector 0.11.0
#--------------------------------------------------------------------------
#                         FastJet release 3.4.0
#                 M. Cacciari, G.P. Salam and G. Soyez                  
#     A software package for jet finding and analysis at colliders      
#                           http://fastjet.fr                           
#	                                                                      
# Please cite EPJC72(2012)1896 [arXiv:1111.6097] if you use this package
# for scientific work and optionally PLB641(2006)57 [hep-ph/0512210].   
#                                                                       
# FastJet is provided without warranty under the GNU GPL v2 or higher.  
# It uses T. Chan's closest pair algorithm, S. Fortune's Voronoi code,
# CGAL and 3rd party plugin jet algorithms. See COPYING file for details.
#--------------------------------------------------------------------------
[          0           5           9 ...  1610612736 -1080418573
           0]
Traceback (most recent call last):
  File "/home/joosep/ml-tau-reco/src/repro.py", line 30, in <module>
    p4_flat = reco_p4[constituents_flat]
  File "/opt/conda/lib/python3.10/site-packages/awkward/highlevel.py", line 956, in __getitem__
    out = self._layout[where]
  File "/opt/conda/lib/python3.10/site-packages/awkward/contents/content.py", line 509, in __getitem__
    return self._getitem(where)
  File "/opt/conda/lib/python3.10/site-packages/awkward/contents/content.py", line 554, in _getitem
    return self._getitem(where.layout)
  File "/opt/conda/lib/python3.10/site-packages/awkward/contents/content.py", line 602, in _getitem
    return self._getitem((where,))
  File "/opt/conda/lib/python3.10/site-packages/awkward/contents/content.py", line 546, in _getitem
    out = next._getitem_next(nextwhere[0], nextwhere[1:], None)
  File "/opt/conda/lib/python3.10/site-packages/awkward/contents/regulararray.py", line 611, in _getitem_next
    down = self._content._getitem_next_jagged(
  File "/opt/conda/lib/python3.10/site-packages/awkward/contents/listoffsetarray.py", line 349, in _getitem_next_jagged
    return out._getitem_next_jagged(slicestarts, slicestops, slicecontent, tail)
  File "/opt/conda/lib/python3.10/site-packages/awkward/contents/listarray.py", line 411, in _getitem_next_jagged
    self._handle_error(
  File "/opt/conda/lib/python3.10/site-packages/awkward/contents/content.py", line 244, in _handle_error
    raise ak._errors.index_error(self, slicer, message)
IndexError: while attempting to slice

    <MomentumArray4D [[{x: 0.328, y: ..., ...}, ...], ...] type='100 * var ...'>

with

    <Array [[], [], [], [], [], ..., [], [], [], [], []] type='100 * var * int32'>

at inner ListArray of length 100, using sub-slice [[], [], [], [], [], [], [], [], [], ..., [], [], [], [], [], [], [], [], []].

Error details: jagged slice's offsets extend beyond its content while attempting to get index 43 (in compiled code: https://github.com/scikit-hep/awkward/blob/awkward-cpp-7/awkward-cpp/src/cpu-kernels/awkward_ListArray_getitem_jagged_apply.cpp#L29).
```

**Comment by chrispap95** [comment]
This looks a lot like the memory issues we have seen in the past because of incorrect object initialization. If it's that then the fix should be easy. I will try to look at it asap.

**Comment by jpata** [comment]
note that the issue does not seem to appear when removing the "event" axis and clustering each event separately:
```python
    for iev in range(len(reco_p4.pt)):
        cluster = fastjet.ClusterSequence(reco_p4[iev], jetdef)
        ci = cluster.constituent_index(min_pt=5.0)
        constituent_index.append(ci)
    constituent_index = ak.from_iter(constituent_index)
```
(in case it's helpful to trace the issue)

**Comment by chrispap95** [comment]
Okay, I fixed it. I will open a PR with more info soon.
